name: Node.js CI with Docker

on:
  push:
    branches:
      - '**'  # Runs on all branches
  pull_request:
    branches:
      - '**'  # Runs on pull requests for all branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-app-test .

    - name: Run tests in Docker container
      run: docker run my-app-test
